In [1]:
#Standard imports 

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import json
import requests as r
%matplotlib inline

In [2]:
#Reference file path

file = '/Users/gta/Desktop/globalterrorismdb_0617dist.csv'

In [3]:
#Read CSV into dataframe.  Forced encoding to 'cp1252 due to error.

df = pd.read_csv(file, encoding='cp1252', low_memory=False)

In [4]:
#Display all values of the columns in a list

df.columns.tolist()

['eventid',
 'iyear',
 'imonth',
 'iday',
 'approxdate',
 'extended',
 'resolution',
 'country',
 'country_txt',
 'region',
 'region_txt',
 'provstate',
 'city',
 'latitude',
 'longitude',
 'specificity',
 'vicinity',
 'location',
 'summary',
 'crit1',
 'crit2',
 'crit3',
 'doubtterr',
 'alternative',
 'alternative_txt',
 'multiple',
 'success',
 'suicide',
 'attacktype1',
 'attacktype1_txt',
 'attacktype2',
 'attacktype2_txt',
 'attacktype3',
 'attacktype3_txt',
 'targtype1',
 'targtype1_txt',
 'targsubtype1',
 'targsubtype1_txt',
 'corp1',
 'target1',
 'natlty1',
 'natlty1_txt',
 'targtype2',
 'targtype2_txt',
 'targsubtype2',
 'targsubtype2_txt',
 'corp2',
 'target2',
 'natlty2',
 'natlty2_txt',
 'targtype3',
 'targtype3_txt',
 'targsubtype3',
 'targsubtype3_txt',
 'corp3',
 'target3',
 'natlty3',
 'natlty3_txt',
 'gname',
 'gsubname',
 'gname2',
 'gsubname2',
 'gname3',
 'gsubname3',
 'motive',
 'guncertain1',
 'guncertain2',
 'guncertain3',
 'individual',
 'nperps',
 'nperpcap',
 'claimed',
 'claimmode',
 'claimmode_txt',
 'claim2',
 'claimmode2',
 'claimmode2_txt',
 'claim3',
 'claimmode3',
 'claimmode3_txt',
 'compclaim',
 'weaptype1',
 'weaptype1_txt',
 'weapsubtype1',
 'weapsubtype1_txt',
 'weaptype2',
 'weaptype2_txt',
 'weapsubtype2',
 'weapsubtype2_txt',
 'weaptype3',
 'weaptype3_txt',
 'weapsubtype3',
 'weapsubtype3_txt',
 'weaptype4',
 'weaptype4_txt',
 'weapsubtype4',
 'weapsubtype4_txt',
 'weapdetail',
 'nkill',
 'nkillus',
 'nkillter',
 'nwound',
 'nwoundus',
 'nwoundte',
 'property',
 'propextent',
 'propextent_txt',
 'propvalue',
 'propcomment',
 'ishostkid',
 'nhostkid',
 'nhostkidus',
 'nhours',
 'ndays',
 'divert',
 'kidhijcountry',
 'ransom',
 'ransomamt',
 'ransomamtus',
 'ransompaid',
 'ransompaidus',
 'ransomnote',
 'hostkidoutcome',
 'hostkidoutcome_txt',
 'nreleased',
 'addnotes',
 'scite1',
 'scite2',
 'scite3',
 'dbsource',
 'INT_LOG',
 'INT_IDEO',
 'INT_MISC',
 'INT_ANY',
 'related']

In [5]:
#Select a portion of the columns and send them to a new dataframe

df = df[['iyear',
 'imonth',
 'iday',
 'country_txt',
 'region_txt',
 'city',
 'latitude',
 'longitude',
 'location',
 'success',
 'suicide',
 'attacktype1_txt',
 'targtype1_txt',
 'natlty1_txt',
 'gname',
 'weaptype1_txt',
 'nkill',
 'nwound']]

In [6]:
df.head()

,iyear,imonth,iday,country_txt,region_txt,city,latitude,longitude,location,success,suicide,attacktype1_txt,targtype1_txt,natlty1_txt,gname,weaptype1_txt,nkill,nwound
0,1970,7,2,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,1,0,Assassination,Private Citizens & Property,Dominican Republic,MANO-D,Unknown,1.0,0.0
1,1970,0,0,Mexico,North America,Mexico city,19.432608,-99.133207,NaN,1,0,Hostage Taking (Kidnapping),Government (Diplomatic),Belgium,23rd of September Communist League,Unknown,0.0,0.0
2,1970,1,0,Philippines,Southeast Asia,Unknown,15.478598,120.599741,NaN,1,0,Assassination,Journalists & Media,United States,Unknown,Unknown,1.0,0.0
3,1970,1,0,Greece,Western Europe,Athens,37.983773,23.728157,NaN,1,0,Bombing/Explosion,Government (Diplomatic),United States,Unknown,Explosives/Bombs/Dynamite,NaN,NaN
4,1970,1,0,Japan,East Asia,Fukouka,33.580412,130.396361,NaN,1,0,Facility/Infrastructure Attack,Government (Diplomatic),United States,Unknown,Incendiary,NaN,NaN

In [7]:
#Generate dictionary needed to rename columns

col_name = {'iyear': 'year',
 'imonth': 'month',
 'iday': 'day',
 'country_txt': 'country',
 'region_txt': 'region',
 'city': 'city',
 'latitude': 'latitude',
 'longitude': 'longitude',
 'location': 'location',
 'success': 'success',
 'suicide': 'sucide',
 'attacktype1_txt': 'type_of_attack',
 'targtype1_txt': 'type_of_target',
 'natlty1_txt': 'nationality',
 'gname': 'group_name',
 'weaptype1_txt': 'type_of_weapon',
 'nkill': 'num_killed',
 'nwound': 'num_wounded'}

In [8]:
#Rename columns based on dict and display head

df = df.rename(columns=col_name)
df.head()

,year,month,day,country,region,city,latitude,longitude,location,success,sucide,type_of_attack,type_of_target,nationality,group_name,type_of_weapon,num_killed,num_wounded
0,1970,7,2,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,1,0,Assassination,Private Citizens & Property,Dominican Republic,MANO-D,Unknown,1.0,0.0
1,1970,0,0,Mexico,North America,Mexico city,19.432608,-99.133207,NaN,1,0,Hostage Taking (Kidnapping),Government (Diplomatic),Belgium,23rd of September Communist League,Unknown,0.0,0.0
2,1970,1,0,Philippines,Southeast Asia,Unknown,15.478598,120.599741,NaN,1,0,Assassination,Journalists & Media,United States,Unknown,Unknown,1.0,0.0
3,1970,1,0,Greece,Western Europe,Athens,37.983773,23.728157,NaN,1,0,Bombing/Explosion,Government (Diplomatic),United States,Unknown,Explosives/Bombs/Dynamite,NaN,NaN
4,1970,1,0,Japan,East Asia,Fukouka,33.580412,130.396361,NaN,1,0,Facility/Infrastructure Attack,Government (Diplomatic),United States,Unknown,Incendiary,NaN,NaN

In [9]:
#Determine the number of sucessful attacks by country

df_country_gb = df[['success', 'country']].groupby(['country'], as_index = False).sum()
df_country_gb.head()

       country  success
0  Afghanistan    10023
1      Albania       63
2      Algeria     2554
3      Andorra        1
4       Angola      480

In [10]:
#Determine the number of sucessful attacks by country and display the top five.

df_country_gb.sort_values(by = ['success'], ascending = False).head()

         country  success
84          Iraq    20075
134     Pakistan    12032
0    Afghanistan    10023
80         India     9480
35      Colombia     7574

In [11]:
#Determine the number of sucessful attacks by country and display the bottom five.


df_country_gb.sort_values(by = ['success'], ascending = False).tail()

          country  success
126  New Hebrides        1
131   North Korea        1
24         Brunei        0
193  Vatican City        0
115     Mauritius        0

In [12]:
#Determine the total number of attacks by type.


df[['type_of_attack', 'country']].groupby(['type_of_attack'], as_index =False).count()

                        type_of_attack  country
0                        Armed Assault    40223
1                        Assassination    18402
2                    Bombing/Explosion    83073
3       Facility/Infrastructure Attack     9581
4                            Hijacking      598
5  Hostage Taking (Barricade Incident)      902
6          Hostage Taking (Kidnapping)    10233
7                      Unarmed Assault      913
8                              Unknown     6425

In [13]:
#Select all rows that where the type_of_attack was a hijacking and send the data to a new dataframe


df_attack_type = df[df['type_of_attack'] == 'Hijacking']

#Show head of new dataframe
df_attack_type.head()

,year,month,day,country,region,city,latitude,longitude,location,success,sucide,type_of_attack,type_of_target,nationality,group_name,type_of_weapon,num_killed,num_wounded
12,1970,1,8,Italy,Western Europe,Rome,41.890520,12.494249,NaN,1,0,Hijacking,Airports & Aircraft,United States,Unknown,Firearms,0.0,0.0
135,1970,3,14,United States,North America,Long Beach,33.766725,-118.192399,Pacific Ocean,1,0,Hijacking,Military,United States,Left-Wing Militants,Fake Weapons,0.0,0.0
162,1970,3,31,Japan,East Asia,Fukouka,33.580412,130.396361,NaN,1,0,Hijacking,Airports & Aircraft,Japan,Japanese Red Army (JRA),Explosives/Bombs/Dynamite,0.0,0.0
379,1970,7,1,Brazil,South America,Rio de Janeiro,-22.908278,-43.197026,NaN,0,0,Hijacking,Airports & Aircraft,Brazil,Unknown,Unknown,0.0,0.0
421,1970,7,22,Greece,Western Europe,Athens,37.979180,23.716647,NaN,1,0,Hijacking,Airports & Aircraft,Greece,Arabs,Firearms,0.0,0.0

In [14]:
#Calculate the total number of attacks by region

df_region_gb = df[['region', 'success']].groupby(['region'], as_index = False).count()

In [15]:
df_region_gb.sort_values(by=['success'], ascending = False)

                         region  success
5    Middle East & North Africa    46511
8                    South Asia    41497
7                 South America    18762
11               Western Europe    16307
10           Sub-Saharan Africa    15491
9                Southeast Asia    11453
1   Central America & Caribbean    10340
4                Eastern Europe     5031
6                 North America     3346
3                     East Asia      794
2                  Central Asia      554
0         Australasia & Oceania      264

In [16]:
#Calculate the total number of attacks by year

df_year_gb = df[['year', 'success']].groupby(['year'], as_index = False).count()
df_year_gb.sort_values(by=['success'], ascending = False)

    year  success
43  2014    16860
44  2015    14852
45  2016    13488
42  2013    11996
41  2012     8500
22  1992     5073
40  2011     5071
39  2010     4822
37  2008     4803
38  2009     4719
21  1991     4683
19  1989     4323
20  1990     3887
18  1988     3720
14  1984     3495
23  1994     3458
36  2007     3241
26  1997     3200
17  1987     3184
24  1995     3081
25  1996     3056
15  1985     2915
13  1983     2870
16  1986     2860
35  2006     2749
10  1980     2662
9   1979     2661
11  1981     2585
12  1982     2545
34  2005     2009
30  2001     1907
29  2000     1813
8   1978     1526
28  1999     1395
31  2002     1332
7   1977     1319
32  2003     1262
33  2004     1162
27  1998      933
6   1976      923
5   1975      740
0   1970      651
4   1974      580
2   1972      496
3   1973      473
1   1971      470

In [17]:
#Calculate the total number of attacks by month

df_month_gb = df[['month', 'success']].groupby(['month'], as_index = False).count()

In [18]:
df_month_gb.sort_values(by=['success'], ascending = False)

    month  success
5       5    15771
7       7    15247
8       8    14802
10     10    14728
3       3    14284
6       6    14258
4       4    14213
11     11    14064
1       1    14036
9       9    13246
2       2    12975
12     12    12706
0       0       20

In [19]:
file = '/Users/gta/Desktop/data_csv.csv'

In [20]:
df_codes = pd.read_csv(file)

In [21]:
col_rename = {'Name': 'country', 'Code': 'code'}

In [22]:
df_codes = df_codes.rename(columns = col_rename)

In [23]:
df_codes.head()

          country code
0     Afghanistan   AF
1   Åland Islands   AX
2         Albania   AL
3         Algeria   DZ
4  American Samoa   AS

In [24]:
df_code_merge = df.merge(df_codes, how='inner', on='country')

In [25]:
df_code_merge.head()

,year,month,day,country,region,city,latitude,longitude,location,success,sucide,type_of_attack,type_of_target,nationality,group_name,type_of_weapon,num_killed,num_wounded,code
0,1970,7,2,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,1,0,Assassination,Private Citizens & Property,Dominican Republic,MANO-D,Unknown,1.0,0.0,DO
1,1970,3,24,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,1,0,Hostage Taking (Kidnapping),Military,United States,Dominican Popular Movement (MPD),Unknown,0.0,0.0,DO
2,1971,1,28,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,1,0,Armed Assault,Educational Institution,Dominican Republic,Tony El Pelou Band,Firearms,0.0,0.0,DO
3,1971,1,28,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,1,0,Armed Assault,Journalists & Media,Dominican Republic,Tony El Pelou Band,Firearms,0.0,0.0,DO
4,1971,5,11,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,0,0,Assassination,Government (General),Dominican Republic,Unknown,Explosives/Bombs/Dynamite,0.0,0.0,DO

In [26]:
#df_code_merge['query_url'] = 'http://api.worldbank.org/v2/countries/' + df_code_merge['code'] + '/indicators/NY.GDP.MKTP.CD?date=' + df_code_merge['year'].map(str) + '&format=json'

In [31]:
df_code_merge['gdp'] = ''
df_code_merge['help_code'] = ''

In [35]:
df_code_merge['help_code'] = df_code_merge['code'] + df_code_merge['year'].map(str)

In [36]:
df_code_merge.head()

,year,month,day,country,region,city,latitude,longitude,location,success,...,type_of_attack,type_of_target,nationality,group_name,type_of_weapon,num_killed,num_wounded,code,gdp,help_code
0,1970,7,2,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,1,...,Assassination,Private Citizens & Property,Dominican Republic,MANO-D,Unknown,1.0,0.0,DO,,DO1970
1,1970,3,24,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,1,...,Hostage Taking (Kidnapping),Military,United States,Dominican Popular Movement (MPD),Unknown,0.0,0.0,DO,,DO1970
2,1971,1,28,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,1,...,Armed Assault,Educational Institution,Dominican Republic,Tony El Pelou Band,Firearms,0.0,0.0,DO,,DO1971
3,1971,1,28,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,1,...,Armed Assault,Journalists & Media,Dominican Republic,Tony El Pelou Band,Firearms,0.0,0.0,DO,,DO1971
4,1971,5,11,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,0,...,Assassination,Government (General),Dominican Republic,Unknown,Explosives/Bombs/Dynamite,0.0,0.0,DO,,DO1971

In [37]:
df_code_merge['query_url'] = 'http://api.worldbank.org/v2/countries/' + df_code_merge['code'] + '/indicators/NY.GDP.MKTP.CD?date=' + df_code_merge['year'].map(str) + '&format=json'

In [38]:
df_code_merge.head()

,year,month,day,country,region,city,latitude,longitude,location,success,...,type_of_target,nationality,group_name,type_of_weapon,num_killed,num_wounded,code,gdp,help_code,query_url
0,1970,7,2,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,1,...,Private Citizens & Property,Dominican Republic,MANO-D,Unknown,1.0,0.0,DO,,DO1970,http://api.worldbank.org/v2/countries/DO/indic...
1,1970,3,24,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,1,...,Military,United States,Dominican Popular Movement (MPD),Unknown,0.0,0.0,DO,,DO1970,http://api.worldbank.org/v2/countries/DO/indic...
2,1971,1,28,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,1,...,Educational Institution,Dominican Republic,Tony El Pelou Band,Firearms,0.0,0.0,DO,,DO1971,http://api.worldbank.org/v2/countries/DO/indic...
3,1971,1,28,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,1,...,Journalists & Media,Dominican Republic,Tony El Pelou Band,Firearms,0.0,0.0,DO,,DO1971,http://api.worldbank.org/v2/countries/DO/indic...
4,1971,5,11,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,0,...,Government (General),Dominican Republic,Unknown,Explosives/Bombs/Dynamite,0.0,0.0,DO,,DO1971,http://api.worldbank.org/v2/countries/DO/indic...

In [29]:
row_count = 0
for index, row in df_code_merge.iterrows():
    
    target_url = 'http://api.worldbank.org/v2/countries/' + row['code'] + '/indicators/NY.GDP.MKTP.CD?date=' + str(row['year']) + '&format=json'
    response = r.get(target_url).json()
    
    try:
        gdp_value = response[1][0]['value']
        df_code_merge.set_value(index, 'gdp', gdp_value)
        print("Now retrieving data from row # " + str(row_count))
        row_count += 1
    
    except:
        print('............Error with data ................................... Skipping' + str(row_count))
        continue 

df_code_merge.head()

Now retrieving data from row # 0
Now retrieving data from row # 1
Now retrieving data from row # 2
Now retrieving data from row # 3
Now retrieving data from row # 4
Now retrieving data from row # 5
Now retrieving data from row # 6
Now retrieving data from row # 7
Now retrieving data from row # 8
Now retrieving data from row # 9
Now retrieving data from row # 10
Now retrieving data from row # 11
Now retrieving data from row # 12
Now retrieving data from row # 13
Now retrieving data from row # 14
Now retrieving data from row # 15
Now retrieving data from row # 16
Now retrieving data from row # 17
Now retrieving data from row # 18
Now retrieving data from row # 19
Now retrieving data from row # 20
Now retrieving data from row # 21
Now retrieving data from row # 22
Now retrieving data from row # 23
Now retrieving data from row # 24
Now retrieving data from row # 25
Now retrieving data from row # 26
Now retrieving data from row # 27
Now retrieving data from row # 28
Now retrieving data from row # 29
Now retrieving data from row # 30
Now retrieving data from row # 31
Now retrieving data from row # 32
Now retrieving data from row # 33
Now retrieving data from row # 34
Now retrieving data from row # 35
Now retrieving data from row # 36
Now retrieving data from row # 37
Now retrieving data from row # 38
Now retrieving data from row # 39
Now retrieving data from row # 40
Now retrieving data from row # 41
Now retrieving data from row # 42
Now retrieving data from row # 43
Now retrieving data from row # 44
Now retrieving data from row # 45
Now retrieving data from row # 46
Now retrieving data from row # 47
Now retrieving data from row # 48
Now retrieving data from row # 49
Now retrieving data from row # 50
Now retrieving data from row # 51
Now retrieving data from row # 52
Now retrieving data from row # 53
Now retrieving data from row # 54
Now retrieving data from row # 55
Now retrieving data from row # 56
Now retrieving data from row # 57
Now retrieving data from row # 58
Now retrieving data from row # 59
Now retrieving data from row # 60
Now retrieving data from row # 61
Now retrieving data from row # 62
Now retrieving data from row # 63
Now retrieving data from row # 64
Now retrieving data from row # 65
Now retrieving data from row # 66
Now retrieving data from row # 67
Now retrieving data from row # 68
Now retrieving data from row # 69
Now retrieving data from row # 70
Now retrieving data from row # 71
Now retrieving data from row # 72
Now retrieving data from row # 73
Now retrieving data from row # 74
Now retrieving data from row # 75
Now retrieving data from row # 76
Now retrieving data from row # 77
Now retrieving data from row # 78
Now retrieving data from row # 79
Now retrieving data from row # 80
Now retrieving data from row # 81
Now retrieving data from row # 82
Now retrieving data from row # 83
Now retrieving data from row # 84
Now retrieving data from row # 85
Now retrieving data from row # 86
Now retrieving data from row # 87
Now retrieving data from row # 88
Now retrieving data from row # 89
Now retrieving data from row # 90
Now retrieving data from row # 91
Now retrieving data from row # 92
Now retrieving data from row # 93
Now retrieving data from row # 94
Now retrieving data from row # 95
Now retrieving data from row # 96
Now retrieving data from row # 97
Now retrieving data from row # 98
Now retrieving data from row # 99
Now retrieving data from row # 100
Now retrieving data from row # 101
Now retrieving data from row # 102
Now retrieving data from row # 103
Now retrieving data from row # 104
Now retrieving data from row # 105
Now retrieving data from row # 106
Now retrieving data from row # 107
Now retrieving data from row # 108
Now retrieving data from row # 109
Now retrieving data from row # 110
Now retrieving data from row # 111
Now retrieving data from row # 112
Now retrieving data from row # 113
Now retrieving data from row # 114
Now retrieving data from row # 115
Now retrieving data from row # 116
Now retrieving data from row # 117
Now retrieving data from row # 118
Now retrieving data from row # 119
Now retrieving data from row # 120
Now retrieving data from row # 121
Now retrieving data from row # 122
Now retrieving data from row # 123
Now retrieving data from row # 124
Now retrieving data from row # 125
Now retrieving data from row # 126
Now retrieving data from row # 127
Now retrieving data from row # 128
Now retrieving data from row # 129
Now retrieving data from row # 130
Now retrieving data from row # 131
Now retrieving data from row # 132
Now retrieving data from row # 133
Now retrieving data from row # 134
Now retrieving data from row # 135
Now retrieving data from row # 136
Now retrieving data from row # 137
Now retrieving data from row # 138
Now retrieving data from row # 139
Now retrieving data from row # 140
Now retrieving data from row # 141
Now retrieving data from row # 142
Now retrieving data from row # 143
Now retrieving data from row # 144
Now retrieving data from row # 145
Now retrieving data from row # 146
Now retrieving data from row # 147
Now retrieving data from row # 148
Now retrieving data from row # 149
Now retrieving data from row # 150
Now retrieving data from row # 151
Now retrieving data from row # 152
Now retrieving data from row # 153
Now retrieving data from row # 154
Now retrieving data from row # 155
Now retrieving data from row # 156
Now retrieving data from row # 157
Now retrieving data from row # 158
Now retrieving data from row # 159
Now retrieving data from row # 160
Now retrieving data from row # 161
Now retrieving data from row # 162
Now retrieving data from row # 163
Now retrieving data from row # 164
Now retrieving data from row # 165
Now retrieving data from row # 166
Now retrieving data from row # 167
Now retrieving data from row # 168
Now retrieving data from row # 169
Now retrieving data from row # 170
Now retrieving data from row # 171
Now retrieving data from row # 172
Now retrieving data from row # 173
Now retrieving data from row # 174
Now retrieving data from row # 175
Now retrieving data from row # 176
Now retrieving data from row # 177
Now retrieving data from row # 178
Now retrieving data from row # 179
Now retrieving data from row # 180
Now retrieving data from row # 181
Now retrieving data from row # 182
Now retrieving data from row # 183
Now retrieving data from row # 184
Now retrieving data from row # 185
Now retrieving data from row # 186
Now retrieving data from row # 187
Now retrieving data from row # 188
Now retrieving data from row # 189
Now retrieving data from row # 190
Now retrieving data from row # 191
Now retrieving data from row # 192
Now retrieving data from row # 193
Now retrieving data from row # 194
Now retrieving data from row # 195
Now retrieving data from row # 196
Now retrieving data from row # 197
Now retrieving data from row # 198
Now retrieving data from row # 199
Now retrieving data from row # 200
Now retrieving data from row # 201
Now retrieving data from row # 202
Now retrieving data from row # 203
Now retrieving data from row # 204
Now retrieving data from row # 205
Now retrieving data from row # 206
Now retrieving data from row # 207
Now retrieving data from row # 208
Now retrieving data from row # 209
Now retrieving data from row # 210
Now retrieving data from row # 211
Now retrieving data from row # 212
Now retrieving data from row # 213
Now retrieving data from row # 214
Now retrieving data from row # 215
Now retrieving data from row # 216
Now retrieving data from row # 217
Now retrieving data from row # 218
Now retrieving data from row # 219
Now retrieving data from row # 220
Now retrieving data from row # 221
Now retrieving data from row # 222
Now retrieving data from row # 223
Now retrieving data from row # 224
Now retrieving data from row # 225
Now retrieving data from row # 226
Now retrieving data from row # 227
Now retrieving data from row # 228
Now retrieving data from row # 229
Now retrieving data from row # 230
Now retrieving data from row # 231
Now retrieving data from row # 232
Now retrieving data from row # 233
Now retrieving data from row # 234
Now retrieving data from row # 235
Now retrieving data from row # 236
Now retrieving data from row # 237

Now retrieving data from row # 238
Now retrieving data from row # 239
Now retrieving data from row # 240
Now retrieving data from row # 241
Now retrieving data from row # 242
Now retrieving data from row # 243
Now retrieving data from row # 244
Now retrieving data from row # 245
Now retrieving data from row # 246
Now retrieving data from row # 247
Now retrieving data from row # 248
Now retrieving data from row # 249
Now retrieving data from row # 250
Now retrieving data from row # 251
Now retrieving data from row # 252
Now retrieving data from row # 253
Now retrieving data from row # 254
Now retrieving data from row # 255
Now retrieving data from row # 256
Now retrieving data from row # 257
Now retrieving data from row # 258
Now retrieving data from row # 259
Now retrieving data from row # 260
Now retrieving data from row # 261
Now retrieving data from row # 262
Now retrieving data from row # 263
Now retrieving data from row # 264
Now retrieving data from row # 265
Now retrieving data from row # 266
Now retrieving data from row # 267
Now retrieving data from row # 268
Now retrieving data from row # 269
Now retrieving data from row # 270
Now retrieving data from row # 271
Now retrieving data from row # 272
Now retrieving data from row # 273
Now retrieving data from row # 274
Now retrieving data from row # 275
Now retrieving data from row # 276
Now retrieving data from row # 277
Now retrieving data from row # 278
Now retrieving data from row # 279
Now retrieving data from row # 280
Now retrieving data from row # 281
Now retrieving data from row # 282
Now retrieving data from row # 283
Now retrieving data from row # 284
Now retrieving data from row # 285
Now retrieving data from row # 286
Now retrieving data from row # 287
Now retrieving data from row # 288
Now retrieving data from row # 289
Now retrieving data from row # 290
Now retrieving data from row # 291
Now retrieving data from row # 292
Now retrieving data from row # 293
Now retrieving data from row # 294
Now retrieving data from row # 295
Now retrieving data from row # 296
Now retrieving data from row # 297
Now retrieving data from row # 298
Now retrieving data from row # 299
Now retrieving data from row # 300
Now retrieving data from row # 301
Now retrieving data from row # 302
Now retrieving data from row # 303
Now retrieving data from row # 304
Now retrieving data from row # 305
Now retrieving data from row # 306
Now retrieving data from row # 307
Now retrieving data from row # 308
Now retrieving data from row # 309
Now retrieving data from row # 310
Now retrieving data from row # 311
Now retrieving data from row # 312
Now retrieving data from row # 313
Now retrieving data from row # 314
Now retrieving data from row # 315
Now retrieving data from row # 316
Now retrieving data from row # 317
Now retrieving data from row # 318
Now retrieving data from row # 319
Now retrieving data from row # 320
Now retrieving data from row # 321
Now retrieving data from row # 322
Now retrieving data from row # 323
Now retrieving data from row # 324
Now retrieving data from row # 325
Now retrieving data from row # 326
Now retrieving data from row # 327
Now retrieving data from row # 328
Now retrieving data from row # 329
Now retrieving data from row # 330
Now retrieving data from row # 331
Now retrieving data from row # 332
Now retrieving data from row # 333
Now retrieving data from row # 334
Now retrieving data from row # 335
Now retrieving data from row # 336
Now retrieving data from row # 337
Now retrieving data from row # 338
Now retrieving data from row # 339
Now retrieving data from row # 340
Now retrieving data from row # 341
Now retrieving data from row # 342

KeyboardInterrupt:

In [30]:
df_code_merge.head(300)

,year,month,day,country,region,city,latitude,longitude,location,success,sucide,type_of_attack,type_of_target,nationality,group_name,type_of_weapon,num_killed,num_wounded,code,gdp
0,1970,7,2,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,1,0,Assassination,Private Citizens & Property,Dominican Republic,MANO-D,Unknown,1.0,0.0,DO,1485400100
1,1970,3,24,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,1,0,Hostage Taking (Kidnapping),Military,United States,Dominican Popular Movement (MPD),Unknown,0.0,0.0,DO,1485400100
2,1971,1,28,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,1,0,Armed Assault,Educational Institution,Dominican Republic,Tony El Pelou Band,Firearms,0.0,0.0,DO,1666400000
3,1971,1,28,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,1,0,Armed Assault,Journalists & Media,Dominican Republic,Tony El Pelou Band,Firearms,0.0,0.0,DO,1666400000
4,1971,5,11,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,0,0,Assassination,Government (General),Dominican Republic,Unknown,Explosives/Bombs/Dynamite,0.0,0.0,DO,1666400000
5,1973,1,2,Dominican Republic,Central America & Caribbean,Santiago de los Caballeros,19.450000,-70.700000,NaN,0,0,Assassination,Private Citizens & Property,Dominican Republic,Red June of 14 June,Firearms,0.0,0.0,DO,2344699900
6,1973,5,9,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,0,0,Hostage Taking (Kidnapping),Government (General),Dominican Republic,Unknown,Unknown,0.0,0.0,DO,2344699900
7,1973,9,28,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,1,0,Hostage Taking (Kidnapping),Government (Diplomatic),Mexico,Unknown,Unknown,0.0,0.0,DO,2344699900
8,1974,9,27,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,1,0,Hostage Taking (Kidnapping),Government (Diplomatic),United States,M12J,Unknown,0.0,0.0,DO,2925600000
9,1974,9,27,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,1,0,Hostage Taking (Barricade Incident),Government (Diplomatic),Venezuela,Dominican Popular Movement (MPD),Firearms,0.0,0.0,DO,2925600000
10,1978,3,26,Dominican Republic,Central America & Caribbean,San Pedro de Macoris,18.455759,-69.307808,NaN,1,0,Armed Assault,Private Citizens & Property,Dominican Republic,Trinitarians,Firearms,3.0,NaN,DO,4774400000
11,1979,2,7,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,1,0,Assassination,Police,Dominican Republic,Unknown,Firearms,1.0,1.0,DO,5498800100
12,1979,4,14,Dominican Republic,Central America & Caribbean,San Pedro de Macoris,18.455759,-69.307808,NaN,1,0,Bombing/Explosion,Educational Institution,Dominican Republic,Unknown,Explosives/Bombs/Dynamite,0.0,0.0,DO,5498800100
13,1980,1,26,Dominican Republic,Central America & Caribbean,Moca,19.396959,-70.522911,NaN,1,0,Armed Assault,Police,Dominican Republic,Unknown,Firearms,1.0,2.0,DO,6631000100
14,1982,4,22,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,1,0,Bombing/Explosion,Government (General),Dominican Republic,Unknown,Explosives/Bombs/Dynamite,NaN,NaN,DO,7964000300
15,1982,6,18,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,1,0,Bombing/Explosion,Government (General),Dominican Republic,Unknown,Explosives/Bombs/Dynamite,5.0,3.0,DO,7964000300
16,1987,7,26,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,1,0,Bombing/Explosion,Private Citizens & Property,Dominican Republic,Maximiliano Gomez Revolutionary Brigade,Explosives/Bombs/Dynamite,0.0,0.0,DO,5.82699e+09
17,1987,7,26,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,1,0,Bombing/Explosion,Private Citizens & Property,Dominican Republic,Maximiliano Gomez Revolutionary Brigade,Explosives/Bombs/Dynamite,0.0,0.0,DO,5.82699e+09
18,1987,7,26,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,1,0,Bombing/Explosion,Private Citizens & Property,Dominican Republic,Maximiliano Gomez Revolutionary Brigade,Explosives/Bombs/Dynamite,0.0,0.0,DO,5.82699e+09
19,1987,7,26,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,1,0,Bombing/Explosion,Private Citizens & Property,Dominican Republic,Maximiliano Gomez Revolutionary Brigade,Explosives/Bombs/Dynamite,0.0,0.0,DO,5.82699e+09
20,1987,7,26,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,1,0,Bombing/Explosion,Business,Dominican Republic,Maximiliano Gomez Revolutionary Brigade,Explosives/Bombs/Dynamite,0.0,0.0,DO,5.82699e+09
21,1987,7,28,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,1,0,Bombing/Explosion,Business,Dominican Republic,Maximiliano Gomez Revolutionary Brigade,Explosives/Bombs/Dynamite,1.0,0.0,DO,5.82699e+09
22,1987,7,28,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,1,0,Bombing/Explosion,Business,Dominican Republic,Maximiliano Gomez Revolutionary Brigade,Explosives/Bombs/Dynamite,1.0,0.0,DO,5.82699e+09
23,1987,7,28,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,1,0,Bombing/Explosion,Business,Dominican Republic,Maximiliano Gomez Revolutionary Brigade,Explosives/Bombs/Dynamite,1.0,0.0,DO,5.82699e+09
24,1987,7,28,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,1,0,Bombing/Explosion,Business,Dominican Republic,Maximiliano Gomez Revolutionary Brigade,Explosives/Bombs/Dynamite,1.0,0.0,DO,5.82699e+09
25,1987,7,28,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,1,0,Bombing/Explosion,Business,Dominican Republic,Maximiliano Gomez Revolutionary Brigade,Explosives/Bombs/Dynamite,1.0,0.0,DO,5.82699e+09
26,1987,7,28,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,1,0,Bombing/Explosion,Business,Dominican Republic,Maximiliano Gomez Revolutionary Brigade,Explosives/Bombs/Dynamite,1.0,0.0,DO,5.82699e+09
27,1987,7,28,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,1,0,Bombing/Explosion,Business,Dominican Republic,Maximiliano Gomez Revolutionary Brigade,Explosives/Bombs/Dynamite,1.0,0.0,DO,5.82699e+09
28,1987,7,28,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,NaN,1,0,Bombing/Explosion,Private Citizens & Property,Dominican Republic,Maximiliano Gomez Revolutionary Brigade,Explosives/Bombs/Dynamite,0.0,0.0,DO,5.82699e+09
29,1987,11,26,Dominican Republic,Central America & Caribbean,Bonao,18.942101,-70.409370,NaN,1,0,Bombing/Explosion,Government (General),Dominican Republic,Unknown,Explosives/Bombs/Dynamite,0.0,4.0,DO,5.82699e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,1994,4,25,Mexico,North America,Unknown,29.297225,-110.330881,NaN,1,0,Hostage Taking (Kidnapping),Business,Mexico,Unknown,Unknown,0.0,0.0,MX,5.27319e+11
271,1994,4,25,Mexico,North America,Mexico City,19.432608,-99.133207,NaN,1,0,Hostage Taking (Kidnapping),Business,Mexico,Unknown,Firearms,0.0,0.0,MX,5.27319e+11
272,1994,4,26,Mexico,North America,San Cristobal de Las Casas,16.738601,-92.633229,NaN,1,0,Assassination,Private Citizens & Property,Mexico,Unknown,Firearms,9.0,0.0,MX,5.27319e+11
273,1994,4,28,Mexico,North America,Tijuana,32.533489,-117.018204,NaN,1,0,Assassination,Police,Mexico,Unknown,Firearms,2.0,0.0,MX,5.27319e+11
274,1994,5,26,Mexico,North America,Mexico City,19.432608,-99.133207,NaN,1,0,Hostage Taking (Kidnapping),Violent Political Party,Mexico,Unknown,Firearms,0.0,0.0,MX,5.27319e+11
275,1994,5,26,Mexico,North America,Mexico City,19.246470,-99.101350,NaN,1,0,Assassination,Police,Mexico,Unknown,Firearms,1.0,0.0,MX,5.27319e+11
276,1994,5,31,Mexico,North America,Iztapalapa,19.358738,-99.094060,NaN,1,0,Armed Assault,Police,Mexico,Francisco Villa People's Front,Melee,0.0,0.0,MX,5.27319e+11
277,1994,6,9,Mexico,North America,Unknown,19.566519,-101.706829,NaN,1,0,Assassination,Government (General),Mexico,Unknown,Vehicle (not to include vehicle-borne explosiv...,1.0,0.0,MX,5.27319e+11
278,1994,6,13,Mexico,North America,Guadalajara,20.673343,-103.344177,NaN,1,0,Bombing/Explosion,Business,Mexico,Unknown,Explosives/Bombs/Dynamite,5.0,12.0,MX,5.27319e+11
279,1994,6,27,Mexico,North America,San Andrés Cholula,19.036019,-98.214348,NaN,1,0,Hostage Taking (Kidnapping),Religious Figures/Institutions,Mexico,Unknown,Firearms,0.0,0.0,MX,5.27319e+11
280,1994,6,28,Mexico,North America,Mazapa de Madero,15.387523,-92.188247,NaN,1,0,Facility/Infrastructure Attack,Government (General),Mexico,People's National Liberation Movement,Firearms,NaN,0.0,MX,5.27319e+11
281,1994,9,6,Mexico,North America,Jaltenango,15.966524,-92.628852,NaN,1,0,Assassination,Violent Political Party,Mexico,Unknown,Firearms,1.0,0.0,MX,5.27319e+11
282,1994,9,28,Mexico,North America,Mexico City,19.432608,-99.133207,NaN,1,0,Assassination,Government (General),Mexico,Unknown,Firearms,1.0,0.0,MX,5.27319e+11
283,1994,9,29,Mexico,North America,Chamula,16.784013,-92.689632,NaN,1,0,Assassination,Private Citizens & Property,Mexico,U/I Catholic Traditionalists,Firearms,3.0,1.0,MX,5.27319e+11
284,1994,10,30,Mexico,North America,Unknown,16.756932,-93.129235,NaN,1,0,Unknown,Violent Political Party,Mexico,Indians,Unknown,0.0,3.0,MX,5.27319e+11
285,1994,10,30,Mexico,North America,Simojovel,17.140579,-92.710906,NaN,1,0,Unknown,Government (General),Mexico,Democratic Revolutionary Party,Unknown,0.0,2.0,MX,5.27319e+11
286,1994,10,30,Mexico,North America,Angel Albino,16.023310,-91.897930,NaN,1,0,Assassination,Government (General),Mexico,White Guard,Firearms,1.0,0.0,MX,5.27319e+11
287,1994,11,8,Mexico,North America,Mexico City,19.432608,-99.133207,NaN,1,0,Unknown,Business,Mexico,Unknown,Unknown,0.0,0.0,MX,5.27319e+11
288,1994,11,18,Mexico,North America,Mexico City,19.432608,-99.133207,NaN,0,0,Bombing/Explosion,Transportation,Peru,Shining Path (SL),Explosives/Bombs/Dynamite,0.0,0.0,MX,5.27319e+11
289,1994,11,27,Mexico,North America,Ciudad Juarez,31.733333,-106.483333,NaN,1,0,Assassination,Police,Mexico,Unknown,Melee,3.0,0.0,MX,5.27319e+11
290,1994,12,31,Mexico,North America,Mexico City,19.432608,-99.133207,NaN,1,0,Assassination,Private Citizens & Property,Costa Rica,Unknown,Melee,1.0,0.0,MX,5.27319e+11
291,1995,1,10,Mexico,North America,Chicomuselo,15.743255,-92.285660,NaN,1,0,Hostage Taking (Kidnapping),Government (General),Mexico,State Council of Indian and Peasant Organization,Unknown,2.0,2.0,MX,3.43793e+11
292,1995,1,11,Mexico,North America,Chicomuselo,15.743255,-92.285660,NaN,0,0,Armed Assault,Government (General),Mexico,Zapatista National Liberation Army,Firearms,6.0,3.0,MX,3.43793e+11
293,1995,1,11,Mexico,North America,Chicomuselo,15.743255,-92.285660,NaN,0,0,Armed Assault,Government (General),Mexico,Zapatista National Liberation Army,Firearms,10.0,0.0,MX,3.43793e+11
294,1995,1,26,Mexico,North America,Mazatlan,23.236111,-106.415278,NaN,1,0,Armed Assault,Business,Mexico,Unknown,Firearms,2.0,3.0,MX,3.43793e+11
295,1995,2,2,Mexico,North America,Mexico City,19.432608,-99.133207,NaN,0,0,Assassination,Violent Political Party,Mexico,Unknown,Firearms,0.0,0.0,MX,3.43793e+11
296,1995,2,6,Mexico,North America,Chiapa de Corzo,16.707486,-93.012251,NaN,1,0,Unknown,Private Citizens & Property,Mexico,Zapatista National Liberation Army,Unknown,0.0,0.0,MX,3.43793e+11
297,1995,2,6,Mexico,North America,Suchiate,14.540831,-92.220917,NaN,1,0,Unknown,Private Citizens & Property,Mexico,Zapatista National Liberation Army,Unknown,0.0,0.0,MX,3.43793e+11
298,1995,2,6,Mexico,North America,Suchiate,14.540831,-92.220917,NaN,1,0,Unknown,Private Citizens & Property,Mexico,Zapatista National Liberation Army,Unknown,0.0,0.0,MX,3.43793e+11
299,1995,2,7,Mexico,North America,San Cristobal de Las Casas,16.738601,-92.633229,NaN,1,0,Hostage Taking (Kidnapping),Government (General),Mexico,Democratic Revolutionary Party,Unknown,0.0,0.0,MX,3.43793e+11